image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    before: |
      npm ci

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0
  - name: Run app
    command: |
      gp sync-await setup

      npm run dev -- --host
  - name: Terminal
    openMode: split-right
    command: |
      gp sync-await setup

ports:
  - port: 5173
    visibility: private

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - waderyan.gitblame
    - svelte.svelte-vscode
    - ms-playwright.playwright
    - esbenp.prettier-vscode
    - sebsojeda.vscode-svx
