tasks:
  - name: Setup
    before: |
      nvm install --lts
      nvm use --lts
      nvm alias default $(node -v | sed 's/v//')
      echo "nvm use default" > ~/.bashrc.d/51-nvm-fix

      curl -sfL gpm.simonemms.com | bash

      gpm install pre-commit

      npm ci

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0
  - name: Run app
    command: |
      gp sync-await setup

      npm run dev -- --host
  - name: Terminal
    openMode: split-right
    command: |
      gp sync-await setup

ports:
  - port: 5173
    visibility: private

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - waderyan.gitblame
    - svelte.svelte-vscode
    - ms-playwright.playwright
    - esbenp.prettier-vscode
    - sebsojeda.vscode-svx
